version: "3.7"
services:
  app:
    build:
      args:
        user: quiz
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: quiz
    container_name: quiz-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./quiz/:/var/www
    networks:
      - quiz
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    restart: unless-stopped
    volumes:
      - db_quiz:/var/lib/mysql
    networks:
      - quiz

  nginx:
    image: nginx:alpine
    container_name: quiz-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./quiz/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - quiz

networks:
  quiz:
    driver: bridge

volumes:
  db_quiz:
    driver: local